# permissions for end users to view gitopsapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitopsapi-viewer-role
rules:
- apiGroups:
  - git.flanksource.com
  resources:
  - gitopsapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - git.flanksource.com
  resources:
  - gitopsapis/status
  verbs:
  - get
