# permissions for end users to edit gitopsapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitopsapi-editor-role
rules:
- apiGroups:
  - git.flanksource.com
  resources:
  - gitopsapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - git.flanksource.com
  resources:
  - gitopsapis/status
  verbs:
  - get
