apiVersion: git.flanksource.com/v1
kind: GitRepository
metadata:
  name: git-operator-test
  namespace: platform-system
spec:
  gitSSH:
    url: git@github.com:flanksource/git-operator-test.git
    secretRef:
      # You need to define a secret named git-operator-test in namespace platform-system with following contents
      # SSH_PRIVATE_KEY=...(pem encoded private key)
      # SSH_PRIVATE_KEY_PASSWORD=...(optional)
      # kubectl create secret generic git-operator-test2 -n platform-system --from-file=SSH_PRIVATE_KEY=$HOME/.ssh/id_rsa
      name: git-operator-test2
      namespace: platform-system